services:
  mongo: 
    image: mongo:6.0
    container_name: chatify_db 
    ports: 
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db 
  chatapp_backend:  
    build: 
          context: /backend
          dockerfile: Dockerfile 
    container_name: chatify_backend
    env_file:
          - ./backend/.env 
    ports: 
          - "3000:3000"
    depends_on: 
          - mongo
  chatapp_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile 
    container_name: chatify_frontend 
    ports: 
      - "5173:5173" 
    depends_on: 
      - chatapp_backend  
volumes: 
  mongo_data: